#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
## AT the 9th word, displays "Hi" before "Best School".
count=0
while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
