#!/usr/bin/env bash
# To displays the time for 12 hours & 59 minutes.
hour=0
while [ "$hour" -le 12 ];
do
  echo "Hour: $hour"
  ((hour++))
  minute=1
  while [ "$minute" -le 59 ];
  do
    echo "$minute"
    (( minute++ ))
  done
 done
